/**
 * Vulnerability deduplication and merge logic.
 *
 * IMPORTANT: Versioning is LOCAL to each node. The `version` field tracks
 * how many times THIS node's copy of the record has been modified. It is
 * never propagated on the mesh — each node maintains its own version history.
 *
 * When a vulnerability arrives via mesh (from KraftCERT or peer gossip),
 * the receiving node deduplicates against its local DB and increments its
 * own local version counter.
 *
 * Dedup key resolution:
 *   1. cve_id (primary — if non-empty)
 *   2. advisory_id (fallback — for advisories without CVE)
 *   3. id (no dedup — unique record)
 *
 * Merge rules:
 *   - Higher-trust source wins for advisory fields (title, description, cvss, affected_products)
 *   - Local status is NEVER overwritten by incoming data
 *   - Local version increments on every merge (local counter, not global)
 *   - Asset info is enriched (union, not overwrite)
 */

import type { Vulnerability, VulnerabilitySource, VulnChangelogEntry, VulnFieldChange } from "@nordlys/contracts";

/** Source trust ranking — higher number = more trusted. */
const SOURCE_TRUST: Record<VulnerabilitySource, number> = {
  kraftcert: 100,
  cisa: 80,
  nvd: 60,
  vendor: 50,
  scanner: 30,
  manual: 10,
};

export interface DedupResult {
  action: "insert" | "update" | "skip";
  record: Vulnerability;
  /** Previous version (if update) */
  previous?: Vulnerability;
  /** Changelog entry generated by this operation */
  changelogEntry?: VulnChangelogEntry;
}

/**
 * Find the dedup key for a vulnerability.
 * Returns the key type and value, or null if no dedup possible.
 */
export function dedupKey(vuln: Vulnerability): { type: "cve" | "advisory"; value: string } | null {
  if (vuln.cve_id && vuln.cve_id.trim() !== "") {
    return { type: "cve", value: vuln.cve_id.trim().toUpperCase() };
  }
  if (vuln.advisory_id && vuln.advisory_id.trim() !== "") {
    return { type: "advisory", value: vuln.advisory_id.trim().toUpperCase() };
  }
  return null;
}

/**
 * Merge an incoming vulnerability with an existing record.
 * Returns the merged result with incremented version.
 *
 * Rules:
 *   - If incoming source has higher trust: overwrite advisory fields
 *   - If same source: overwrite advisory fields (newer data)
 *   - If lower trust: only enrich (add missing asset/products info)
 *   - NEVER touch: status, id, created_at
 *   - ALWAYS: increment version, update updated_at
 */
export function mergeVulnerability(
  existing: Vulnerability,
  incoming: Vulnerability,
  localNodeId?: string,
): DedupResult {
  const existingTrust = SOURCE_TRUST[existing.source] ?? 0;
  const incomingTrust = SOURCE_TRUST[incoming.source] ?? 0;

  const now = new Date().toISOString();
  const newVersion = (existing.version ?? 1) + 1;
  const isHighTrust = incomingTrust >= existingTrust;

  // Track field changes
  const changes: VulnFieldChange[] = [];

  function track(field: string, oldVal: string | undefined | null, newVal: string | undefined | null) {
    const o = oldVal ?? undefined;
    const n = newVal ?? undefined;
    if (o !== n) {
      changes.push({ field, old_value: o, new_value: n });
    }
  }

  let merged: Vulnerability;

  if (isHighTrust) {
    // Higher or same trust: overwrite advisory fields
    track("title", existing.title, incoming.title || existing.title);
    track("description", existing.description, incoming.description || existing.description);
    track("cvss_score", String(existing.cvss_score), String(incoming.cvss_score));
    track("severity", existing.severity, incoming.severity);
    track("source", existing.source, incoming.source);
    track("cve_id", existing.cve_id, incoming.cve_id || existing.cve_id);
    track("advisory_id", existing.advisory_id, incoming.advisory_id || existing.advisory_id);
    track("reference_url", existing.reference_url, incoming.reference_url || existing.reference_url);
    track("tlp", existing.tlp, incoming.tlp ?? existing.tlp);
    track("asset", existing.asset, incoming.asset || existing.asset);

    merged = {
      ...existing,
      title: incoming.title || existing.title,
      description: incoming.description || existing.description,
      cvss_score: incoming.cvss_score,
      severity: incoming.severity,
      cve_id: incoming.cve_id || existing.cve_id,
      advisory_id: incoming.advisory_id || existing.advisory_id,
      reference_url: incoming.reference_url || existing.reference_url,
      tlp: incoming.tlp ?? existing.tlp,
      signed_by: incoming.signed_by ?? existing.signed_by,
      signature: incoming.signature ?? existing.signature,
      source: incoming.source,
      affected_products: mergeProducts(existing.affected_products, incoming.affected_products),
      asset: incoming.asset || existing.asset,
      // Preserve local state
      status: existing.status,
      id: existing.id,
      created_at: existing.created_at,
      // Bump version
      version: newVersion,
      updated_at: now,
      updated_by: localNodeId,
    };
  } else {
    // Lower trust: enrich only
    track("asset", existing.asset, existing.asset || incoming.asset);
    track("cve_id", existing.cve_id, existing.cve_id || incoming.cve_id);

    merged = {
      ...existing,
      asset: existing.asset || incoming.asset,
      cve_id: existing.cve_id || incoming.cve_id,
      affected_products: mergeProducts(existing.affected_products, incoming.affected_products),
      version: newVersion,
      updated_at: now,
      updated_by: localNodeId,
    };
  }

  // Build changelog entry
  const entry: VulnChangelogEntry = {
    version: newVersion,
    timestamp: now,
    action: isHighTrust ? "merge_high_trust" : "merge_low_trust",
    source: incoming.source,
    source_trust: incomingTrust,
    changes: changes.filter((c) => c.old_value !== c.new_value),
    note: isHighTrust && incoming.source !== existing.source
      ? `${incoming.source} (trust ${incomingTrust}) overrode ${existing.source} (trust ${existingTrust})`
      : undefined,
  };

  // Append to changelog
  merged.changelog = [...(existing.changelog ?? []), entry];

  return { action: "update", record: merged, previous: existing, changelogEntry: entry };
}

/**
 * Process an incoming vulnerability against an existing collection.
 * Returns the dedup result with the action to take.
 */
export function dedup(
  incoming: Vulnerability,
  existing: Vulnerability[],
  localNodeId?: string,
): DedupResult {
  const key = dedupKey(incoming);

  if (key) {
    const match = existing.find((v) => {
      const vKey = dedupKey(v);
      return vKey?.type === key.type && vKey?.value === key.value;
    });

    if (match) {
      return mergeVulnerability(match, incoming, localNodeId);
    }
  }

  // No match — insert as new record (version 1)
  const initialEntry: VulnChangelogEntry = {
    version: 1,
    timestamp: incoming.created_at || new Date().toISOString(),
    action: "initial_import",
    source: incoming.source,
    source_trust: SOURCE_TRUST[incoming.source] ?? 0,
    changes: [],
  };

  const record: Vulnerability = {
    ...incoming,
    version: 1,
    status: incoming.status ?? "new",
    updated_by: localNodeId,
    changelog: [initialEntry],
  };

  return { action: "insert", record, changelogEntry: initialEntry };
}

/**
 * Batch dedup: process multiple incoming vulns against existing collection.
 * Returns updated collection + list of actions taken.
 */
export function dedupBatch(
  incomingList: Vulnerability[],
  existing: Vulnerability[],
  localNodeId?: string,
): { collection: Vulnerability[]; results: DedupResult[] } {
  // Work on a mutable copy
  const collection = [...existing];
  const results: DedupResult[] = [];

  for (const incoming of incomingList) {
    const result = dedup(incoming, collection, localNodeId);
    results.push(result);

    if (result.action === "insert") {
      collection.push(result.record);
    } else if (result.action === "update") {
      const idx = collection.findIndex((v) => v.id === result.record.id);
      if (idx >= 0) collection[idx] = result.record;
    }
  }

  return { collection, results };
}

// ── Helpers ──────────────────────────────────────────────────────────

function mergeProducts(
  a?: { product: string; version: string }[],
  b?: { product: string; version: string }[],
): { product: string; version: string }[] | undefined {
  if (!a && !b) return undefined;
  const map = new Map<string, { product: string; version: string }>();
  for (const p of a ?? []) map.set(`${p.product}||${p.version}`, p);
  for (const p of b ?? []) map.set(`${p.product}||${p.version}`, p);
  return [...map.values()];
}
